title: Marcos Rivas
logo: "/images/logo.png?raw=true"
description: > 
  ¡Hola! deja y me presento, mi nombre es MarcosAquí encontrarás la información relacionada con mi educación y mi 
  experiencia laboral, lo que no encontrarás es que soy una persona 
  que le gusta levantarse con un propósito cada día, aprender algo nuevo, me gusta sentir que voy para adelante, tanto 
  en mi vida laboral como 
  en mi vida personal, y algo que no puede faltar aquí es decirte que soy una persona curiosa, si no se algo lo aprendo. Y de algo 
  que estoy seguro es que voy a tratar de ser una mejor persona cada día.  
google_analytics: UA-67867780-2
