title: Marcos Rivas
logo: "/images/logo.png?raw=true"
description: > 
  En este espacio encontrarás toda la información relacionada con mi educación y mi experiencia laboral.
  Huehuetenango, Guatemala. 
  <br>
  xlopez3000@gmail.com
  Tel: (502) 3443 2011
  
theme: jekyll-theme-minimal
google_analytics: UA-67867780-2
