title: Marcos Rivas
logo: "/images/logo.png?raw=true"
description: > 
  Huehuetenango, Guatemala. 
  <br><br>
  xlopez3000@gmail.com
  <br>
  Tel: (502) 3443 2011
  
theme: jekyll-theme-minimal
google_analytics: UA-67867780-2
